---
- hosts: all
  roles:
    - fedora
  vars:
    - common_packages:
      - vim
      - git
      - wget
      - openssh
      - net-tools
      - firewalld
      - zip
      - gzip
      - bzip2
      - curl
      - dialog
      - nfs-utils
      - xinetd
      - tar
      - m4
      - mkpasswd
  remote_user: root
  tasks:
  - include: users/users.yml

  - name: update all currently installed packages to latest versions
    dnf: name=* state=latest

  - name: install common tools
    dnf: name={{ item }} state=present
    with_items: "{{common_packages}}"

  - name: install development tools
    dnf: name="@^Development tools" state=present

  - name: disable selinux
    command: setenforce 0

  - name: put selinux in permissive mode
    selinux: policy=targeted state=permissive

  - name: start and enable firewalld
    service: name=firewall-cmd state=started enabled=yes

  - name: ssh firewall configs
    firewalld: service=ssh permanent=true state=enabled
    notify: Restart firewalld

  - name: write ssh config file
    template: src=/srv/fedora/common/templates/sshd_config.j2 dest=/etc/ssh/sshd_config

  - name: write login.defs file
    template: src=/srv/fedora/common/templates/login.defs.j2 dest=/etc/login.defs

  - name: write system-auth-ac file
    template: src=/srv/fedora/common/templates/system-auth-ac.j2 dest=/etc/pam.d/system-auth-ac
    notify: Restart ssh

  handlers:
  - name: Start and enable firewalld
    service:
      name: firewall-cmd
      state: started
      enabled: yes
  - name: Restart firewalld
    service:
      name: firewall-cmd
      state: restarted
  - name: Restart ssh
    service:
      name: ssh
      state: restarted
