---
- hosts: webservers
  roles:
    - nginx
    - rhel
  vars:
    - nginx_packages:
      - nginx
      - httpd-tools
      - php
      - php-common
      - php-fpm
      - php-gd
      - php-mysqlnd
      - php-pgsql
      - php-xml
      - php-xmlrpc
      - openssl
      - openssl-devel
  remote_user: deploybot
  tasks:
  - name: install nginx and php tools
    yum: state=present name={{ item }}
    with_items: "{{nginx_packages}}"

  - name: enable nginx with system boot
    service: name=nginx state=started enabled=yes

  - name: create vhosts and templates directory
    file:
      - path=/etc/nginx/vhosts state=directory mode=0755
      - path=/etc/nginx/templates state=directory mode=0755
      - path=/etc/nginx/ssl state=directory mode=0755

  - name: import nginx template files into templates
    template:
      - src=/srv/roles/rhel/web/nginx/templates/http_vhost.j2 dest=/etc/nginx/templates/http_vhost
      - src=/srv/roles/rhel/web/nginx/templates/https_vhost.j2 dest=/etc/nginx/templates/https_vhost
      - src=/srv/roles/rhel/web/nginx/templates/combined_vhost.j2 dest=/etc/nginx/templates/combined_vhost

  - name: import php config file
    template:
      - src=/srv/roles/rhel/web/nginx/files/php.j2 dest=/etc/php.ini
      - src=/srv/roles/rhel/web/nginx/files/php-fpm.j2 dest=/etc/php-fpm.d/www.conf

  - name: start and enable php-fpm service
    service: name=php-fpm state=started enabled=yes

  - name: import nginx config file
    template: src=/srv/roles/rhel/web/nginx/templates/nginx.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx
      - restart php-fpm

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

  - name: restart php-fpm
    service:
      name: php-fpm
      state: restarted
