---

  - name: Update all pkgs - SUSE
    zypper:
      name: '*'
      state: latest
    when:
      - ansible_os_family == "Suse"

  - name: Update all patches - SUSE
    zypper:
      name: '*'
      state: latest
      type: patch
    when:
      - ansible_os_family == "Suse"

  - name: Install base pkgs - SUSE
    zypper:
      name: '{{ item }}'
      state: present
    with_items: '{{ var_suse_pkgs }}'
    when:
      - ansible_os_family == "Suse"

  - name: Install devel packages
    command: 'zypper -n in -R -t pattern devel_basis'
