---
- hosts: webservers
  roles:
    - apache
    - rhel
  vars:
    - apache_packages:
      - httpd
      - httpd-tools
      - mod_ssl
      - php
      - php-common
      - php-gd
      - php-xml
      - php-xmlrpc
      - openssl
      - openssl-devel
  remote_user: deploybot
  tasks:
  - name: install apache2 and php tools
    yum: state=present name={{ item }}
    with_items: "{{apache_packages}}"
    notify: start apache

  - name: enable apache2 with system boot
    service: name=httpd enabled=yes

  - name: create vhosts and templates directories
    file:
      - path=/etc/httpd/vhosts state=directory mode=0755
      - path=/etc/httpd/templates state=directory mode=0755
      - path=/etc/httpd/ssl state=directory mode=0755

  - name: import apache2 template files into templates
    template:
      - src=/srv/roles/rhel/web/httpd/templates/http_vhost.j2 /etc/httpd/templates/http_vhost.conf
      - src=/srv/roles/rhel/web/httpd/templates/https_vhost.j2 /etc/httpd/templates/https_vhost.conf
      - src=/srv/roles/rhel/web/httpd/templates/combined_vhost.j2 /etc/httpd/templates/combined_vhost.conf

  - name: import php config file
    template: src=/srv/roles/rhel/web/httpd/files/php.j2 dest=/etc/php.ini

  - name: import apache2 mod_ssl conf file
    template: src=/srv/roles/rhel/web/httpd/files/ssl.j2 dest=/etc/httpd/conf.d/ssl.conf

  - name: import base apache2 config file
    template: src=/srv/roles/rhel/web/httpd/files/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify: restart apache

  handlers:
  - name: start apache
    service:
      name: httpd
      state: started

  - name: restart apache
    service:
      name: httpd
      state: restarted
