---
- hosts: all
  roles:
    - ubuntu
  vars:
    - common_packages:
      - vim
      - git
      - wget
      - openssh
      - net-tools
      - firewalld
      - zip
      - gzip
      - bzip2
      - curl
      - dialog
      - nfs-utils
      - xinetd
      - tar
      - m4
      - mkpasswd
  remote_user: root
  tasks:
  - include: users/users.yml

  - name: update all currently installed packages to latest versions
    apt: update_cache=yes upgrade=dist

  - name: install common tools
    apt: name={{ item }} state=present
    with_items: "{{common_packages}}"

  - name: install development tools
    apt: name=build-essentials state=present

  - name: start and enable ufw
    service: name=ufw state=started
    ufw: state=enabled policy=deny

  - name: ssh firewall configs
    ufw: rule=allow port=22
    notify: Restart UFW

  - name: write ssh config file
    template: src=/srv/ubuntu/common/templates/sshd_config.j2 dest=/etc/ssh/sshd_config

  - name: write login.defs file
    template: src=/srv/ubuntu/common/templates/login.defs.j2 dest=/etc/login.defs

  - name: write system-auth-ac file
    template: src=/srv/ubuntu/common/templates/system-auth-ac.j2 dest=/etc/pam.d/system-auth-ac
    notify: Restart ssh

  handlers:
  - name: Restart UFW
    service:
      name: ufw
      state: restarted
  - name: Restart ssh
    service:
      name: ssh
      state: restarted
