---

- hosts: all
  become: yes
  become_user: root

  pre_tasks:
    - name: Load OS specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_os_family | lower }}.yml"

  tasks:
    - name: Load OS family specific tasks
      include_tasks: "{{ item }}"
      with_first_found:
        - "tasks/{{ ansible_os_family | lower }}.yml"

    - name: Set SELinux mode
      selinux:
        policy: targeted
        state: '{{ item }}'
      with_items:
        - permissive
